# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.tweet_manager:
      class: AppBundle\Manager\TweetManager
      arguments:
        - "@=service('doctrine').getManager()"
        - "%app_tweet_nb_last%"

  app.email_messenger:
      class: AppBundle\Messenger\EmailMessenger
      arguments:
        - "@mailer"