<?php

namespace AppBundle\Repository;

/**
 * tweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tweetRepository extends \Doctrine\ORM\EntityRepository
{
}
